# Generated by Django 3.1.1 on 2020-10-07 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='modules',
            field=models.ManyToManyField(related_name='Modules', to='api.Module'),
        ),
        migrations.AlterField(
            model_name='module',
            name='name',
            field=models.CharField(choices=[('Picture', 'Picture'), ('CarPooling', 'CarPooling'), ('Music', 'Music'), ('TriCount', 'TriCount'), ('Poll', 'Poll')], max_length=10),
        ),
        migrations.AlterField(
            model_name='participate',
            name='creator',
            field=models.BooleanField(verbose_name='creator'),
        ),
    ]
