# Generated by Django 3.1.1 on 2020-09-29 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Picture', 'Picture'), ('CarPooling', 'CarPooling'), ('Music', 'Music'), ('TriCount', 'TriCount'), ('Poll', 'Poll')], max_length=25)),
                ('events', models.ManyToManyField(to='api.Event')),
            ],
        ),
    ]
