# Generated by Django 3.1.1 on 2020-10-07 17:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0002_auto_20201007_1723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participate',
            name='creator',
            field=models.BooleanField(verbose_name='Creator of the event'),
        ),
        migrations.AlterUniqueTogether(
            name='participate',
            unique_together={('event', 'user')},
        ),
    ]
