# Generated by Django 3.1.1 on 2020-10-13 07:40

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0004_auto_20201012_1316'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Participate',
            new_name='Guest',
        ),
    ]
