# Generated by Django 3.1.1 on 2020-10-13 08:09

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0005_auto_20201013_0740'),
    ]

    operations = [
        migrations.RenameField(
            model_name='guest',
            old_name='events',
            new_name='event',
        ),
        migrations.RenameField(
            model_name='guest',
            old_name='users',
            new_name='user',
        ),
        migrations.AlterUniqueTogether(
            name='guest',
            unique_together={('event', 'user')},
        ),
    ]
